version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    network_mode: bridge
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "nest_dev"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: