version: '3'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTRGES_DB: "db_dev"
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db: